site_name: mfsm pro
theme:
  name: material
  features:
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

